#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build/Publish

on:
  push:
    branches: 
      - master

jobs:
  nightly-build-publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - 
        name: Prepare
        id: prep
        run: |
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo ::set-output name=short_sha1::${SHORT_SHA1}
          # VERSION file contains 7.yy.0-SNAPSHOT but for nightlies we want just a nightly tag
          # VERSION=$(head -n 1 VERSION)
          # echo ::set-output name=version::${VERSION}
          echo ::set-output name=version::nightly
          IMAGE=che-devfile-registry
          echo ::set-output name=image::${IMAGE}
          PLATFORMS=$(cat PLATFORMS)
          echo ::set-output name=platforms::${PLATFORMS}
      -
        name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      -
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      -
        name: "Docker quay.io Login"
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - 
        name: Login to docker.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push base images
        run: /bin/bash arbitrary-users-patch/build_images.sh --push

      - name: Build and push happy path image
        run: /bin/bash arbitrary-users-patch/happy-path/build_happy_path_image.sh --push
      -
        name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfiles/Dockerfile
          platforms: ${{ steps.package.outputs.content }}
          tags:  quay.io/eclipse/${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.version }},quay.io/eclipse/${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.short_sha1 }}
          push: true 
